[pytest]

addopts = -v --tb=short --strict-markers -p no:warnings --html=reports/report.html --self-contained-html
# looks for tests in the tests directory, and any files that match the pattern test_*.py
testpaths = tests

# custom markers to label our tests (e.g., api, ui)
markers = 
    api: Run API integration tests
    ui: Run UI/Selenium tests
    db: Run DB related tests
    oauth: OAuth 2.0 API test cases
    smoke: Run smoke tests (will execute fast and give quick results)
    regression: Run regression tests

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_cli_date_format = %H:%M:%S

log_file = logs/automation.log
log_file_level = INFO
log_file_format = %(asctime)s [%(levelname)s] %(filename)s:%(lineno)d - %(message)s
log_file_date_format = %Y-%m-%d %H:%M:%S